# fly.toml app configuration file generated for shimpyo-backend on 2023-05-07T19:12:36+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shimpyo-backend"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"
processes = []

[build]

[env]
TZ = "Asia/Seoul"

[experimental]
auto_rollback = true

[[services]]
http_checks = []
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80
http_options = { response = { headers = { access-control-allow-origin = "*", to-remove = false } } }

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
